import type { State } from "./states";

export const guideDescriptions: Record<State["code"], string> = {
  "AL": "Understand Alabama total-loss valuation, itemized deductions, settlement taxes and fees, and salvage titles. Start with Venfour’s free preliminary valuation.",
  "AK": "Understand Alaska total-loss comparisons, settlement deductions, required policy appraisal, and salvage titles. Start with Venfour’s free preliminary valuation.",
  "AZ": "Understand Arizona comparable-vehicle settlements, taxes and fees, documented deductions, and salvage titles. Start with Venfour’s free preliminary valuation.",
  "AR": "Understand Arkansas total-loss comparisons, transfer costs, salvage-title qualifications, and dispute options. Start with Venfour’s free preliminary valuation.",
  "CA": "Understand California total-loss valuations, settlement taxes and fees, salvage titles, and dispute options. Start with Venfour’s free preliminary valuation.",
  "CO": "Understand Colorado total-loss market value, taxes and title fees, hail-loss distinctions, and dispute options. Start with Venfour’s free preliminary valuation.",
  "CT": "Understand Connecticut’s total-loss valuation sources, calculation disclosure, taxes, salvage titles, and arbitration. Start with Venfour’s free preliminary valuation.",
  "DE": "Understand Delaware total-loss value, replacement-vehicle document-fee credits, salvage retention, and arbitration. Start with Venfour’s free preliminary valuation.",
  "DC": "Understand District of Columbia total-loss valuations, salvage titles, rental coverage, and dispute options. Start with Venfour’s free preliminary valuation.",
  "FL": "Understand Florida total-loss comparables, itemized deductions, deferred sales tax, title rules, and mediation. Start with Venfour’s free preliminary valuation.",
  "GA": "Understand Georgia total-loss valuations, local comparables, taxes, salvage titles, and options for requesting a review.",
  "HI": "Understand Hawaii total-loss valuations, replacement-vehicle tax deadlines, salvage requirements, and options for reviewing an offer.",
  "ID": "Understand Idaho total-loss valuations, settlement taxes, salvage buybacks, title requirements, and options for disputing an offer.",
  "IL": "Understand Illinois total-loss valuations, deductions, replacement taxes, owner-retention rules, and options for reviewing an offer.",
  "IN": "Understand Indiana total-loss offers, settlement sales tax, salvage-title steps, vehicle excise refunds, and insurance review options.",
  "IA": "Understand Iowa total-loss valuations, comparable-vehicle recourse, taxes and registration fees, salvage titles, and review options.",
  "KS": "Understand Kansas total-loss valuations, local-market comparisons, taxes and fees, replacement recourse, and salvage-title rules.",
  "KY": "Understand Kentucky total-loss valuations, taxes, replacement-value recourse, salvage-title qualifications, and insurance review options.",
  "LA": "Understand Louisiana total-loss valuations, local market evidence, salvage classifications, and review options. Start with Venfour’s free preliminary valuation.",
  "ME": "Understand Maine total-loss valuations, regional comparables, sales-tax-credit coverage, and appraisal options. Start with Venfour’s free preliminary valuation.",
  "MD": "Understand Maryland total-loss valuations, comparable vehicles, taxes, valuation disclosures, and appraisal options. Start with Venfour’s free preliminary valuation.",
  "MA": "Understand Massachusetts total-loss valuations, rental coverage, retained vehicles, and salvage titles. Start with Venfour’s free preliminary valuation.",
  "MI": "Review Michigan total-loss offers, policy deductions, claim documentation, and salvage title requirements. Start with Venfour’s free preliminary valuation.",
  "MN": "Understand Minnesota total-loss valuations, local comparables, settlement taxes and fees, and appraisal options. Start with Venfour’s free preliminary valuation.",
  "MS": "Understand Mississippi total-loss valuation, policy terms, salvage classifications, and consumer assistance. Start with Venfour’s free preliminary valuation.",
  "MO": "Understand Missouri total-loss valuations, deductions, replacement-vehicle tax allowances, and your options. Start with Venfour’s free preliminary valuation.",
  "MT": "Understand Montana total-loss valuations, local market evidence, valuation records, and retained salvage. Start with Venfour’s free preliminary valuation.",
  "NE": "Understand Nebraska total-loss values, replacement-tax guidance, registration refunds, and qualified salvage rules. Start with Venfour’s free preliminary valuation.",
  "NV": "Understand Nevada comparable values, written deductions, settlement taxes and fees, and salvage exceptions. Start with Venfour’s free preliminary valuation.",
  "NH": "Understand New Hampshire total-loss valuations, report access, qualified reconsideration rights, and salvage rules. Start with Venfour’s free preliminary valuation.",
  "NJ": "Understand New Jersey total-loss offers, itemized reports, sales tax, written reconsideration, and salvage options. Start with Venfour’s free preliminary valuation.",
  "NM": "Understand New Mexico total-loss disputes, policy deductions, replacement excise tax, and salvage-title distinctions. Start with Venfour’s free preliminary valuation.",
  "NY": "Understand New York total-loss values, sales tax, the qualified right of recourse, and salvage branding. Start with Venfour’s free preliminary valuation.",
  "NC": "Understand North Carolina total-loss values, taxes, owner-retained salvage, and supporting deductions. Start with Venfour’s free preliminary valuation.",
  "ND": "Understand North Dakota total-loss values, salvage deductions, replacement excise-tax credits, and title rules. Start with Venfour’s free preliminary valuation.",
  "OH": "Review Ohio total-loss valuations, replacement sales-tax reimbursement, claim documents, and owner-retained salvage.",
  "OK": "Understand Oklahoma total-loss cash settlements, taxes and deductions, rental questions, and salvage-title considerations.",
  "OR": "Review Oregon total-loss valuations, undisputed payments, salvage titles, and appraisal options before responding to an offer.",
  "PA": "Understand Pennsylvania total-loss appraisal reports, replacement value, applicable sales tax, and owner-retained salvage.",
  "RI": "Check Rhode Island total-loss value, taxes and deductions, replacement recourse, and salvage-title requirements.",
  "SC": "Review South Carolina total-loss market value, rental and claim timing, salvage titles, and insurance complaint options.",
  "SD": "Understand South Dakota total-loss value, nonbinding appraisal, salvage titles, and the conditional tax credit for a replacement lease.",
  "TN": "Review Tennessee total-loss vehicle value, coverage questions, salvage and rebuilt titles, and options for resolving a valuation disagreement.",
  "TX": "Understand Texas total-loss valuations, salvage deductions, replacement-vehicle taxes, and dispute options. Start with Venfour’s free preliminary valuation.",
  "UT": "Understand Utah total-loss values, third-party deductions, transportation costs, and salvage titles. Start with Venfour’s free preliminary valuation.",
  "VT": "Understand Vermont total-loss valuation methods, taxes, condition deductions, and valuation disclosures. Start with Venfour’s free preliminary valuation.",
  "VA": "Understand Virginia total-loss valuations, deduction records, storage notices, and policy appraisal options. Start with Venfour’s free preliminary valuation.",
  "WA": "Understand Washington total-loss values, valuation reports, taxes, salvage deductions, and appraisal rights. Start with Venfour’s free preliminary valuation.",
  "WV": "Understand West Virginia total-loss guide values, sales tax, deductions, and salvage classifications. Start with Venfour’s free preliminary valuation.",
  "WI": "Understand Wisconsin total-loss market values, local comparison evidence, deductibles, and salvage titles. Start with Venfour’s free preliminary valuation.",
  "WY": "Understand Wyoming total-loss claim documentation, coverage terms, rental limits, and salvage titles. Start with Venfour’s free preliminary valuation."
};
