begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
set local storage.allow_delete_query='true';
select no_plan();
insert into auth.users(id,email,email_confirmed_at,is_anonymous) values
 ('e8100000-0000-4000-8000-000000000001','referral-manager@example.test',statement_timestamp(),false),
 ('e8100000-0000-4000-8000-000000000002','referral-staff@example.test',statement_timestamp(),false),
 ('e8100000-0000-4000-8000-000000000003','referral-contact@example.test',statement_timestamp(),false),
 ('e8100000-0000-4000-8000-000000000004','referral-other@example.test',statement_timestamp(),false),
 ('e8100000-0000-4000-8000-000000000005','referral-unverified@example.test',null,false),
 ('e8100000-0000-4000-8000-000000000006','referral-anonymous@example.test',statement_timestamp(),true);
insert into public.staff_members(user_id) values
 ('e8100000-0000-4000-8000-000000000001'),('e8100000-0000-4000-8000-000000000002'),('e8100000-0000-4000-8000-000000000006');
insert into public.referral_partner_managers(user_id) values
 ('e8100000-0000-4000-8000-000000000001'),('e8100000-0000-4000-8000-000000000004'),('e8100000-0000-4000-8000-000000000006');
create temporary table referral_fixture(key text primary key,value jsonb) on commit drop;
grant all on referral_fixture to authenticated,service_role;
select ok(not has_function_privilege('anon','public.referral_partner_operation(text,jsonb)','EXECUTE'),'anonymous cannot call referral operations');
select ok(not has_function_privilege('authenticated','public.referral_partner_worker(text,jsonb)','EXECUTE'),'browser cannot call job worker');
select ok(not has_function_privilege('service_role','public.referral_partner_operation(text,jsonb)','EXECUTE'),'service credentials do not act as a partner manager');
select ok(not has_table_privilege('authenticated','public.referral_partner_managers','INSERT'),'browser cannot grant manager permission');
select ok(not has_table_privilege('authenticated','public.referral_partners','SELECT'),'partner data is exposed only by bounded projections');
select ok(not has_table_privilege('authenticated','public.referral_partner_jobs','SELECT'),'prepared email requests stay private');
select ok(not has_function_privilege('authenticated','public.referral_partner_detail_internal(uuid,boolean)','EXECUTE'),'internal projections are not public');
select ok((select not public and file_size_limit=10485760 from storage.buckets where id='partner-agreements'),'agreement bucket is private and limited to 10MiB');
select is(public.dispatch_referral_partner_jobs(),null::bigint,'unconfigured scheduler is inert');

set local role authenticated;
select set_config('request.jwt.claim.sub','e8100000-0000-4000-8000-000000000002',true);
select is(public.referral_partner_operation('access')->>'is_partner_manager','false','ordinary staff cannot manage partners');
select throws_ok($$select public.referral_partner_operation('staff_list')$$,'42501',null,'staff-only manager request denied');
select set_config('request.jwt.claim.sub','e8100000-0000-4000-8000-000000000004',true);
select is(public.referral_partner_operation('access')->>'is_partner_manager','false','manager permission alone cannot replace staff membership');
select set_config('request.jwt.claim.sub','e8100000-0000-4000-8000-000000000006',true);
select is(public.referral_partner_operation('access')->>'is_partner_manager','false','anonymous identity cannot manage partners even with both rows');
select set_config('request.jwt.claim.sub','e8100000-0000-4000-8000-000000000005',true);
select throws_ok($$select public.referral_partner_operation('partner_list')$$,'42501',null,'unverified identity denied');
select set_config('request.jwt.claim.sub','e8100000-0000-4000-8000-000000000001',true);
select is(public.referral_partner_operation('access')->>'is_partner_manager','true','verified designated staff manager authorized');
select throws_ok($$select public.referral_partner_operation('staff_list','{"page_size":101}')$$,'22023',null,'unbounded page denied');
select throws_ok($$select public.referral_partner_operation('staff_create','{"request_id":"e8200000-0000-4000-8000-000000000001","business_name":"Fixture Shop","contact_email":"referral-contact@example.test","commission_amount_minor_units":0}')$$,'22023',null,'zero commission denied');
insert into referral_fixture values('create_request','{"request_id":"e8200000-0000-4000-8000-000000000002","business_name":"Fixture Shop","contact_email":"referral-contact@example.test","commission_amount_minor_units":2500}');
insert into referral_fixture values('detail',public.referral_partner_operation('staff_create',(select value from referral_fixture where key='create_request')));
select is((select value#>>'{partner,status}' from referral_fixture where key='detail'),'onboarding','new business begins onboarding');
select is(public.referral_partner_operation('staff_create',(select value from referral_fixture where key='create_request')),(select value from referral_fixture where key='detail'),'exact create replay returns original result');
select throws_ok($$select public.referral_partner_operation('staff_create',(select value||'{"business_name":"Changed"}'::jsonb from referral_fixture where key='create_request'))$$,'40001',null,'same request with changed content conflicts');
insert into referral_fixture values('partner_id',(select value#>'{partner,id}' from referral_fixture where key='detail'));
-- Production starts without seeded templates; this assertion is scoped to the fixture identity.
reset role;
select is((select count(*) from public.referral_partner_templates where created_by_user_id='e8100000-0000-4000-8000-000000000001'),0::bigint,'migration seeds no template for test manager');
set local role authenticated;
insert into referral_fixture values('template',public.referral_partner_operation('template_save',jsonb_build_object('request_id',gen_random_uuid(),'title','Fixture referral agreement','sections',jsonb_build_array(jsonb_build_object('heading','Program terms','body','Fictional test terms. Commission applies only to qualified purchases.')))));
select is((select value#>>'{template,status}' from referral_fixture where key='template'),'draft','template editor saves a draft');
update referral_fixture set value=public.referral_partner_operation('template_publish',jsonb_build_object('request_id',gen_random_uuid(),'template_id',value#>>'{template,id}','expected_revision',(value#>>'{template,revision}')::integer)) where key='template';
select is((select value#>>'{template,status}' from referral_fixture where key='template'),'published','manager publishes immutable template');
select throws_ok($$select public.referral_partner_operation('template_save',jsonb_build_object('request_id',gen_random_uuid(),'template_id',value#>>'{template,id}','expected_revision',(value#>>'{template,revision}')::integer,'title','Changed','sections','[{"heading":"Changed","body":"Changed"}]'::jsonb)) from referral_fixture where key='template'$$,'55000',null,'published template cannot be edited');
update referral_fixture set value=public.referral_partner_operation('invite',jsonb_build_object('request_id',gen_random_uuid(),'partner_id',value#>>'{partner,id}','expected_revision',(value#>>'{partner,revision}')::integer)) where key='detail';
insert into referral_fixture values('first_invitation',(select value#>'{invitations,0,id}' from referral_fixture where key='detail'));
select is((select value#>>'{invitations,0,status}' from referral_fixture where key='detail'),'pending','invitation is persisted');
update referral_fixture set value=public.referral_partner_operation('resend',jsonb_build_object('request_id',gen_random_uuid(),'partner_id',value#>>'{partner,id}','expected_revision',(value#>>'{partner,revision}')::integer)) where key='detail';
insert into referral_fixture values('invitation_id',(select to_jsonb(x->>'id') from referral_fixture f cross join lateral jsonb_array_elements(f.value->'invitations') x where f.key='detail' and x->>'status'='pending'));
select is((select count(*) from referral_fixture f cross join lateral jsonb_array_elements(f.value->'invitations') x where f.key='detail' and x->>'status'='revoked'),1::bigint,'resend revokes prior invitation credential');
select set_config('request.jwt.claim.sub','e8100000-0000-4000-8000-000000000004',true);
select throws_ok($$select public.referral_partner_operation('invitation_get',jsonb_build_object('invitation_id',(select value#>>'{}' from referral_fixture where key='invitation_id')))$$,'42501',null,'invitation UUID alone does not authorize another email');
select throws_ok($$select public.referral_partner_operation('partner_get',jsonb_build_object('partner_id',(select value#>>'{}' from referral_fixture where key='partner_id')))$$,'42501',null,'other account cannot read partner profile');
select set_config('request.jwt.claim.sub','e8100000-0000-4000-8000-000000000003',true);
select throws_ok($$select public.referral_partner_operation('invitation_accept',jsonb_build_object('request_id',gen_random_uuid(),'invitation_id',(select value#>>'{}' from referral_fixture where key='first_invitation')))$$,'55000',null,'revoked invite cannot be accepted');
select is(public.referral_partner_operation('invitation_get',jsonb_build_object('invitation_id',(select value#>>'{}' from referral_fixture where key='invitation_id')))->'invitation'->>'status','pending','verified intended contact can review invite');
reset role;
update public.referral_partner_invitations set expires_at=statement_timestamp()-interval '1 minute' where id=(select (value#>>'{}')::uuid from referral_fixture where key='invitation_id');
set local role authenticated;
select throws_ok($$select public.referral_partner_operation('invitation_accept',jsonb_build_object('request_id',gen_random_uuid(),'invitation_id',(select value#>>'{}' from referral_fixture where key='invitation_id')))$$,'55000',null,'expired invitation cannot be accepted');
reset role;
update public.referral_partner_invitations set expires_at=statement_timestamp()+interval '7 days' where id=(select (value#>>'{}')::uuid from referral_fixture where key='invitation_id');
set local role authenticated;

update referral_fixture set value=public.referral_partner_operation('invitation_accept',jsonb_build_object('request_id',gen_random_uuid(),'invitation_id',(select value#>>'{}' from referral_fixture where key='invitation_id'))) where key='detail';
select is((select value#>>'{partner,user_id}' from referral_fixture where key='detail'),'e8100000-0000-4000-8000-000000000003','explicit acceptance binds exact verified identity');
select is(public.referral_partner_operation('access')->>'is_partner','true','accepted contact has partner access');
select throws_ok($$select public.referral_partner_operation('agreement_prepare',jsonb_build_object('request_id',gen_random_uuid(),'partner_id',value#>>'{partner,id}','expected_revision',(value#>>'{partner,revision}')::integer)) from referral_fixture where key='detail'$$,'55000',null,'incomplete profile cannot reach signing');
update referral_fixture set value=public.referral_partner_operation('profile_save',jsonb_build_object('request_id',gen_random_uuid(),'partner_id',value#>>'{partner,id}','expected_revision',(value#>>'{partner,revision}')::integer,
 'legal_business_name','Fixture Shop LLC','address_line1','100 Test Street','address_line2',null,'city','Test City','state','MO','postal_code','63101','country','US','contact_name','Test Contact','contact_title','Owner')) where key='detail';
update referral_fixture set value=public.referral_partner_operation('agreement_prepare',jsonb_build_object('request_id',gen_random_uuid(),'partner_id',value#>>'{partner,id}','expected_revision',(value#>>'{partner,revision}')::integer)) where key='detail';
insert into referral_fixture values('agreement',(select value->'agreements'->0 from referral_fixture where key='detail'));
select is((select value#>>'{snapshot,commission_amount_minor_units}' from referral_fixture where key='agreement'),'2500','issued agreement freezes USD commission');
select is((select value#>>'{snapshot,legal_business_name}' from referral_fixture where key='agreement'),'Fixture Shop LLC','issued agreement freezes legal identity');
insert into referral_fixture values('sign_request',(select jsonb_build_object('request_id',gen_random_uuid(),'agreement_id',value->>'id','expected_revision',(value->>'revision')::integer,'agreement_digest',value->>'agreement_digest','typed_legal_name','Test Contact','electronic_consent',true,'pdf_email_consent',true,'authority_confirmed',true) from referral_fixture where key='agreement'));
select throws_ok($$select public.referral_partner_operation('sign',(select value||'{"electronic_consent":false}'::jsonb from referral_fixture where key='sign_request'))$$,'22023',null,'electronic consent is required');
select throws_ok($$select public.referral_partner_operation('sign',(select value||jsonb_build_object('agreement_digest',repeat('0',64)) from referral_fixture where key='sign_request'))$$,'40001',null,'stale agreement content cannot be signed');
update referral_fixture set value=public.referral_partner_operation('sign',(select value from referral_fixture where key='sign_request')) where key='detail';
select is((select value#>>'{partner,status}' from referral_fixture where key='detail'),'awaiting_approval','partner signature awaits manager approval');
select is(public.referral_partner_operation('sign',(select value from referral_fixture where key='sign_request')),(select value from referral_fixture where key='detail'),'sign replay preserves exact timestamp and evidence');
reset role;
select is((select count(*) from public.referral_partner_signatures where agreement_id=(select (value->>'id')::uuid from referral_fixture where key='agreement')),1::bigint,'partner acceptance creates one immutable signature record');
update auth.users set email='changed-referral-contact@example.test' where id='e8100000-0000-4000-8000-000000000003';
set local role authenticated;
select throws_ok($$select public.referral_partner_operation('sign',(select value from referral_fixture where key='sign_request'))$$,'42501',null,'changed verified email cannot replay prior signing request');
reset role;
update auth.users set email='referral-contact@example.test' where id='e8100000-0000-4000-8000-000000000003';
set local role authenticated;
select set_config('request.jwt.claim.sub','e8100000-0000-4000-8000-000000000001',true);
-- A changed offer before activation requires a newly prepared and newly signed agreement.
update referral_fixture set value=public.referral_partner_operation('staff_edit',jsonb_build_object('request_id',gen_random_uuid(),'partner_id',value#>>'{partner,id}','expected_revision',(value#>>'{partner,revision}')::integer,'business_name','Fixture Shop','state','MO','commission_amount_minor_units',3000)) where key='detail';
select is((select value#>>'{partner,status}' from referral_fixture where key='detail'),'onboarding','pre-activation change returns partner to onboarding');
select is((select x->>'status' from referral_fixture f cross join lateral jsonb_array_elements(f.value->'agreements') x where f.key='detail' and x->>'id'=(select value->>'id' from referral_fixture where key='agreement')),'superseded','old signed agreement is superseded');
select ok((select x->'partner_signature' is not null and x->'partner_signature'<>'null'::jsonb from referral_fixture f cross join lateral jsonb_array_elements(f.value->'agreements') x where f.key='detail' and x->>'id'=(select value->>'id' from referral_fixture where key='agreement')),'superseded agreement preserves original signature');
select set_config('request.jwt.claim.sub','e8100000-0000-4000-8000-000000000003',true);
update referral_fixture set value=public.referral_partner_operation('agreement_prepare',jsonb_build_object('request_id',gen_random_uuid(),'partner_id',value#>>'{partner,id}','expected_revision',(value#>>'{partner,revision}')::integer)) where key='detail';
update referral_fixture set value=(select x from referral_fixture f cross join lateral jsonb_array_elements(f.value->'agreements') x where f.key='detail' and x->>'status'='prepared') where key='agreement';
update referral_fixture set value=(select jsonb_build_object('request_id',gen_random_uuid(),'agreement_id',value->>'id','expected_revision',(value->>'revision')::integer,'agreement_digest',value->>'agreement_digest','typed_legal_name','Test Contact','electronic_consent',true,'pdf_email_consent',true,'authority_confirmed',true) from referral_fixture where key='agreement') where key='sign_request';
update referral_fixture set value=public.referral_partner_operation('sign',(select value from referral_fixture where key='sign_request')) where key='detail';
select set_config('request.jwt.claim.sub','e8100000-0000-4000-8000-000000000001',true);
update referral_fixture set value=(select x from referral_fixture f cross join lateral jsonb_array_elements(f.value->'agreements') x where f.key='detail' and x->>'status'='partner_signed') where key='agreement';
insert into referral_fixture values('countersign_request',(select jsonb_build_object('request_id',gen_random_uuid(),'agreement_id',value->>'id','expected_revision',(value->>'revision')::integer,'agreement_digest',value->>'agreement_digest','typed_legal_name','Test Manager','typed_title','Director','electronic_consent',true,'pdf_email_consent',true,'authority_confirmed',true) from referral_fixture where key='agreement'));
update referral_fixture set value=public.referral_partner_operation('countersign',(select value from referral_fixture where key='countersign_request')) where key='detail';
select is((select value#>>'{partner,status}' from referral_fixture where key='detail'),'active','manager countersign atomically activates partner before PDF completion');
select ok(not (select value::text ~ 'prepared_payload|prepared_provider|lease_token' from referral_fixture where key='detail'),'partner detail does not expose worker delivery internals');
select is((select x->>'document_status' from referral_fixture f cross join lateral jsonb_array_elements(f.value->'agreements') x where f.key='detail' and x->>'status'='countersigned'),'queued','final PDF is queued separately');
select is(public.referral_partner_operation('countersign',(select value from referral_fixture where key='countersign_request')),(select value from referral_fixture where key='detail'),'exact countersign replay does not enqueue twice');
select throws_ok($$select public.referral_partner_operation('staff_edit',jsonb_build_object('request_id',gen_random_uuid(),'partner_id',value#>>'{partner,id}','expected_revision',(value#>>'{partner,revision}')::integer,'business_name','Changed','state','MO','commission_amount_minor_units',3500)) from referral_fixture where key='detail'$$,'55000',null,'active contract editing is outside this release');
reset role;
select is((select count(*) from public.referral_partner_signatures where agreement_id=(select (value->>'id')::uuid from referral_fixture where key='agreement')),2::bigint,'countersign stores second separate immutable signature');
select throws_ok($$update public.referral_partner_signatures set signature='{}' where agreement_id=(select (value->>'id')::uuid from referral_fixture where key='agreement')$$,'55000',null,'stored signature cannot be overwritten');
select throws_ok($$update public.referral_partner_agreements set snapshot='{}' where id=(select (value->>'id')::uuid from referral_fixture where key='agreement')$$,'55000',null,'frozen signed snapshot cannot be overwritten');
-- Lease only this fixture's jobs; unrelated committed deliveries remain untouched.
set local role service_role;
insert into referral_fixture values('job',public.referral_partner_worker('lease_document',jsonb_build_object('lease_token','e8300000-0000-4000-8000-000000000001','partner_id',(select value#>>'{}' from referral_fixture where key='partner_id'))));
select is((select value->>'kind' from referral_fixture where key='job'),'document','worker leases frozen final document');
select ok((select value->>'first_attempt_at' is not null from referral_fixture where key='job'),'first lease records stable attempt start');
select throws_ok($$select public.referral_partner_worker('fail_document',jsonb_build_object('job_id',value->>'id','lease_token','e8300000-0000-4000-8000-000000000099','error_code','RENDER_FAILED')) from referral_fixture where key='job'$$,'40001',null,'wrong fencing token cannot finish work');
select public.referral_partner_worker('fail_document',jsonb_build_object('job_id',value->>'id','lease_token',value->>'lease_token','error_code','RENDER_FAILED')) from referral_fixture where key='job';
set local role authenticated;
select is(public.referral_partner_operation('staff_get',jsonb_build_object('partner_id',(select value#>>'{}' from referral_fixture where key='partner_id')))->'partner'->>'status','active','failed PDF leaves prior signatures and active account intact');
update referral_fixture set value=public.referral_partner_operation('staff_get',jsonb_build_object('partner_id',(select value#>>'{}' from referral_fixture where key='partner_id'))) where key='detail';
update referral_fixture set value=(select x from referral_fixture f cross join lateral jsonb_array_elements(f.value->'agreements') x where f.key='detail' and x->>'status'='countersigned') where key='agreement';
select public.referral_partner_operation('document_retry',jsonb_build_object('request_id',gen_random_uuid(),'agreement_id',value->>'id','expected_revision',(value->>'revision')::integer)) from referral_fixture where key='agreement';
set local role service_role;
update referral_fixture set value=public.referral_partner_worker('lease_document',jsonb_build_object('lease_token','e8300000-0000-4000-8000-000000000002','partner_id',(select value#>>'{}' from referral_fixture where key='partner_id'))) where key='job';
select throws_ok($$select public.referral_partner_worker('finish_document',jsonb_build_object('job_id',value->>'id','lease_token',value->>'lease_token','sha256',repeat('a',64),'byte_size',128)) from referral_fixture where key='job'$$,'55000',null,'cannot seal PDF before exact private object exists');
reset role;
insert into storage.objects(bucket_id,name,metadata) select value#>>'{payload,bucket}',value#>>'{payload,object_path}','{"size":128,"mimetype":"application/pdf"}' from referral_fixture where key='job';
set local role service_role;
select public.referral_partner_worker('finish_document',jsonb_build_object('job_id',value->>'id','lease_token',value->>'lease_token','sha256',repeat('a',64),'byte_size',128)) from referral_fixture where key='job';
select throws_ok($$select public.referral_partner_worker('finish_document',jsonb_build_object('job_id',value->>'id','lease_token',value->>'lease_token','sha256',repeat('a',64),'byte_size',128)) from referral_fixture where key='job'$$,'40001',null,'completed document lease cannot finalize twice');
insert into referral_fixture values('email_job',public.referral_partner_worker('lease_email',jsonb_build_object('lease_token','e8300000-0000-4000-8000-000000000003','partner_id',(select value#>>'{}' from referral_fixture where key='partner_id'))));
select is((select value#>>'{payload,kind}' from referral_fixture where key='email_job'),'agreement_copy','sealed PDF queues copy only for the partner');
select is((select value#>>'{payload,recipient_email}' from referral_fixture where key='email_job'),'referral-contact@example.test','copy recipient comes from immutable verified snapshot');
select public.referral_partner_worker('prepare_email',jsonb_build_object('job_id',value->>'id','lease_token',value->>'lease_token','provider','resend','payload',jsonb_build_object('to','referral-contact@example.test','subject','Fixture agreement'))) from referral_fixture where key='email_job';
select is(public.referral_partner_worker('prepare_email',jsonb_build_object('job_id',value->>'id','lease_token',value->>'lease_token','provider','resend','payload',jsonb_build_object('to','changed@example.test')))->'prepared_payload'->>'to','referral-contact@example.test','prepared provider request is frozen across retries') from referral_fixture where key='email_job';
select public.referral_partner_worker('finish_email',jsonb_build_object('job_id',value->>'id','lease_token',value->>'lease_token','provider_message_id','fixture-delivery-id')) from referral_fixture where key='email_job';
reset role;
select throws_ok($$delete from storage.objects where bucket_id='partner-agreements' and name=(select value#>>'{payload,object_path}' from referral_fixture where key='job')$$,'55000',null,'sealed agreement cannot be deleted');
select throws_ok($$update storage.objects set metadata='{"size":2}' where bucket_id='partner-agreements' and name=(select value#>>'{payload,object_path}' from referral_fixture where key='job')$$,'55000',null,'sealed agreement cannot be overwritten');
set local role authenticated;
select set_config('request.jwt.claim.sub','e8100000-0000-4000-8000-000000000003',true);
select is(public.referral_partner_operation('agreement_document',jsonb_build_object('agreement_id',(select value->>'id' from referral_fixture where key='agreement')))->>'sha256',repeat('a',64),'partner can authorize own sealed PDF');
select throws_ok($$select public.referral_partner_operation('staff_agreement_document',jsonb_build_object('agreement_id',(select value->>'id' from referral_fixture where key='agreement')))$$,'42501',null,'owner cannot use staff document endpoint without manager permission');
select set_config('request.jwt.claim.sub','e8100000-0000-4000-8000-000000000004',true);
select throws_ok($$select public.referral_partner_operation('agreement_document',jsonb_build_object('agreement_id',(select value->>'id' from referral_fixture where key='agreement')))$$,'42501',null,'other account cannot access sealed agreement');
select set_config('request.jwt.claim.sub','e8100000-0000-4000-8000-000000000001',true);
select is(public.referral_partner_operation('staff_agreement_document',jsonb_build_object('agreement_id',(select value->>'id' from referral_fixture where key='agreement')))->>'sha256',repeat('a',64),'current designated manager can authorize sealed PDF');
reset role;
delete from public.referral_partner_managers where user_id='e8100000-0000-4000-8000-000000000001';
set local role authenticated;
select throws_ok($$select public.referral_partner_operation('staff_get',jsonb_build_object('partner_id',(select value#>>'{}' from referral_fixture where key='partner_id')))$$,'42501',null,'same-token permission revocation blocks staff read');
select throws_ok($$select public.referral_partner_operation('countersign',(select value from referral_fixture where key='countersign_request'))$$,'42501',null,'same-token permission revocation blocks mutation replay');
select throws_ok($$select public.referral_partner_operation('staff_agreement_document',jsonb_build_object('agreement_id',(select value->>'id' from referral_fixture where key='agreement')))$$,'42501',null,'same-token permission revocation blocks fresh download authorization');
reset role;
select * from finish();
rollback;
