begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select plan(23);
select is((select count(*)::integer from public.jurisdiction_authority_publications),0,'zero reviewed publications');
select is((select count(*)::integer from public.jurisdiction_delivery_authority),0,'zero operating epochs');
select is((select count(*)::integer from public.jurisdiction_attestations),0,'zero credentials and document releases');
select is((select count(*)::integer from public.jurisdiction_document_acceptances),0,'no retroactive acceptance');
select is((select canonical_json::jsonb->'authorized_reviewers' from public.jurisdiction_authority_config),'[]'::jsonb,'empty reviewers');
select is((select canonical_json::jsonb->'attestation_writers' from public.jurisdiction_authority_config),'[]'::jsonb,'empty writers');
select is((select canonical_json::jsonb->'publishers' from public.jurisdiction_authority_config),'[]'::jsonb,'empty publishers');
select ok(not has_function_privilege('service_role','public.publish_jurisdiction_authority(text,text,jsonb)','EXECUTE'),'service cannot publish');
select ok(not has_function_privilege('authenticated','public.publish_jurisdiction_authority(text,text,jsonb)','EXECUTE'),'staff/customer cannot publish');
select ok(not has_function_privilege('anon','public.publish_jurisdiction_authority(text,text,jsonb)','EXECUTE'),'anonymous cannot publish');
select ok(not has_table_privilege('service_role','public.jurisdiction_authority_config','INSERT'),'service cannot self-grant');
select ok(not has_table_privilege('authenticated','public.jurisdiction_authority_config','INSERT'),'customer cannot self-grant');
select ok(not has_table_privilege('jurisdiction_publisher','public.jurisdiction_authority_config','INSERT'),'publisher cannot grant reviewer authority');
select ok(not has_table_privilege('jurisdiction_attestor','jurisdiction_private.review_keys','SELECT'),'writer cannot read other signing keys');
select ok(not has_table_privilege('service_role','jurisdiction_private.review_keys','SELECT'),'service cannot forge review authenticators');
select ok(not has_table_privilege('authenticated','public.jurisdiction_attestations','INSERT'),'partner cannot attest credentials');
select ok(not has_function_privilege('service_role','public.publish_jurisdiction_attestation(text,text)','EXECUTE'),'service cannot attest credentials');
select ok(not has_table_privilege('service_role','public.jurisdiction_document_acceptances','INSERT'),'service cannot claim customer acceptance');
select ok(has_function_privilege('authenticated','public.accept_jurisdiction_document(uuid,uuid,bigint,text,uuid)','EXECUTE'),'authenticated acceptance seam exists');
select ok(not has_function_privilege('service_role','public.accept_jurisdiction_document(uuid,uuid,bigint,text,uuid)','EXECUTE'),'service key alone cannot accept');
select throws_ok($$insert into public.jurisdiction_delivery_authority(revision,registry_digest) values(1,repeat('a',64))$$,'42501','Reviewed publication required for authority','bare authority edit rejected');
select throws_ok($$update public.jurisdiction_authority_config set canonical_json='{}'$$,'55000','Jurisdiction history is append-only.','reviewer history cannot be rewritten');
select ok(not exists(select 1 from pg_auth_members m join pg_roles r on r.oid=m.roleid where r.rolname in ('jurisdiction_publisher','jurisdiction_attestor')),'no release role memberships provisioned');
select * from finish();
rollback;
