/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=production --include-runtime=false --strict-vars=false --env-interface=ProductionWorkerEnvironment worker/environment.d.ts` (hash: 20b0f90d17cd62ea5f669e4131a79718)
interface __BaseEnv_ProductionWorkerEnvironment {
	ASSETS: Fetcher;
	API_ORIGIN: string;
	DEPLOYMENT_ENVIRONMENT: string;
	API_PROXY_SECRET: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_ProductionWorkerEnvironment {}
}
interface ProductionWorkerEnvironment extends __BaseEnv_ProductionWorkerEnvironment {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "API_ORIGIN" | "DEPLOYMENT_ENVIRONMENT" | "API_PROXY_SECRET">> {}
}
