/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=production --include-runtime=false --strict-vars=false --env-interface=ProductionWorkerEnvironment worker/environment.d.ts` (hash: bc13f8daa6728c130a7bf6b732302b43)
interface __BaseEnv_ProductionWorkerEnvironment {
	ASSETS: Fetcher;
	API_ORIGIN: string;
	DEPLOYMENT_ENVIRONMENT: string;
	GOOGLE_ADS_MEASUREMENT: string;
	API_PROXY_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_ProductionWorkerEnvironment {}
}
interface ProductionWorkerEnvironment extends __BaseEnv_ProductionWorkerEnvironment {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "API_ORIGIN" | "DEPLOYMENT_ENVIRONMENT" | "GOOGLE_ADS_MEASUREMENT" | "API_PROXY_SECRET">> {}
}
