import {useState} from 'react';
import './launcher.css';
const stages=[['result','Your result'],['insurer','Insurer explanation'],['market','Market evidence'],['meaning','Comparison meaning'],['request','Prepare request'],['send','Review and send'],['sent','Sent completion']] as const;
const fixtureDescriptions:Record<string,string>={full:'Six market listings, three insurer comparables, complete headline values.',singular:'One market listing and one insurer comparable; the selected range is a single price.',sparse:'Missing range values and no detailed listing rows, to inspect sparse layouts.',long:'Long vehicle, insurer, and owner labels with the full evidence set.'};
export function Launcher(){
 const[fixture,setFixture]=useState('full');
 const href=(mode:string,stage='result',resume=false)=>`/?mode=${mode}&fixture=${fixture}&${resume?'resume=1':`stage=${stage}&reset=1`}`;
 return <main className="synthetic-launcher"><div className="launcher-heading"><span>Venfour · Local review</span><h1>Synthetic launcher</h1><p>Explore the current completed-analysis experience with synthetic cases. No real customer data, payments, provider requests, or email delivery.</p></div><section className="launcher-fixture"><label htmlFor="fixture">Evidence fixture</label><select id="fixture" value={fixture} onChange={event=>setFixture(event.target.value)}><option value="full">Full evidence</option><option value="singular">Single comparable</option><option value="sparse">Sparse evidence</option><option value="long">Long labels</option></select><p>{fixtureDescriptions[fixture]}</p></section><div className="launcher-flows">{(['report','manual'] as const).map(mode=><section className="launcher-flow" key={mode}><h2>{mode==='report'?'Report-upload journey':'Manual / no-report journey'}</h2><p>{mode==='report'?'6 stages + Sent completion':'5 stages + Sent completion'}</p><div className="launcher-actions"><a className="launcher-primary" href={href(mode)}>Start {mode==='report'?'Report':'Manual'} flow <span aria-hidden="true">→</span></a><a href={href(mode,'result',true)}>Resume saved {mode} flow</a></div><h3>Open a specific stage</h3><ol>{stages.filter(([stage])=>mode==='report'||stage!=='insurer').map(([stage,label])=><li key={stage}><a href={href(mode,stage)}>{label}<span aria-hidden="true">↗</span></a></li>)}</ol></section>)}</div><aside className="launcher-notes"><h2>How this works</h2><p><strong>Start or a stage link resets</strong> the selected journey and fixture. A stage link seeds the necessary prior review progress; Review and send includes a saved email draft.</p><p><strong>Resume and refresh preserve</strong> your synthetic progress, draft edits, and sent state in this browser. Each journey and fixture has its own saved state.</p><p><strong>Copy email and Open email are intercepted.</strong> They exercise the interface and record the action without changing your clipboard or opening an email app. View report / Download PDF open a local fixture document.</p><p>At the bottom of each case, open <strong>Synthetic checks</strong> for request logs and optional save/conflict/report-error controls.</p><p className="launcher-utility-links"><a href="/?page=preview">Preliminary analysis</a><a href="/?page=home">Public homepage</a></p></aside></main>;
}
