import './state';
import {useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {createBrowserRouter,RouterProvider,useParams,useLocation} from 'react-router';
import {AppShell} from '@/components/app-shell';
import {BlueButtonHover} from '@/components/ui/blue-button-hover';
import {AuthContext} from '@/features/auth/auth-context';
import {CookieConsentContext} from '@/features/privacy/cookie-consent-context';
import {CompletedAnalysis} from '@/features/total-loss-claim/components/completed-analysis';
import {useTotalLossClaimQuery} from '@/features/total-loss-claim/queries';
import {PublicHomePage} from '@/pages/home-page';
import {TotalLossAnalysisPage} from '@/pages/total-loss-analysis-page';
import {CASE_ID,USER_ID,BASE} from './fixtures';
import {page,mode,storageKey} from './state';
import {Launcher} from './launcher';
import './styles.css';
const user={id:USER_ID,email:'owner@example.com',user_metadata:{full_name:'Case Owner'},app_metadata:{provider:'email'},aud:'authenticated',created_at:'2026-08-29T18:00:00.000Z'};
const session={access_token:'synthetic-access-token',refresh_token:'synthetic-refresh-token',expires_in:3600,token_type:'bearer',user};
const noop=async()=>{};
const auth:any={auth:page==='home'?{status:'signedOut',session:null,user:null}:{status:'signedIn',identity:'permanent',session,user},ensureGuestSession:async()=>session,restoreSession:async()=>session,runTurnstileChallenge:noop,signInWithGoogle:noop,sendMagicLink:noop,completeAuthCallback:async()=>session,completeEmailAuthCallback:async()=>session,signOut:noop};
const consent:any={consent:null,globalPrivacyControl:false,bannerVisible:false,preferencesOpen:false,acceptAll:noop,rejectNonEssential:noop,savePreferences:noop,openPreferences:noop,setPreferencesOpen:noop};
function Harness(){const{stage='result'}=useParams();const location=useLocation();useEffect(()=>localStorage.setItem(`${storageKey}-path`,`${location.pathname}${location.search}`),[location.pathname,location.search]);const query=useTotalLossClaimQuery({accessToken:session.access_token,caseId:CASE_ID,userId:USER_ID});if(query.isError)return <p role="alert">{query.error.message}</p>;if(!query.data||query.data.state!=='secured'||!query.data.report)return <p>Loading synthetic report…</p>;return <CompletedAnalysis accessToken={session.access_token} caseId={CASE_ID} claim={query.data} intakeMode={mode} onRefresh={query.refetch} report={query.data.report} userId={USER_ID} view={`review_${stage.replaceAll('-','_')}` as any}/>;}
const router=createBrowserRouter(page==='launcher'?[{path:'/',element:<Launcher/>}]:[{element:<AppShell/>,children:[{path:`${BASE}/review/:stage`,element:<Harness/>},{path:'/total-loss/cases/:caseId/analysis',element:<TotalLossAnalysisPage/>},{path:'/',element:<PublicHomePage/>}]}]);
const runtime=globalThis as any;const root=runtime.__reviewRoot||=createRoot(document.getElementById('root')!);const queryClient=runtime.__reviewQueryClient||=new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}});
root.render(<QueryClientProvider client={queryClient}><BlueButtonHover/><AuthContext.Provider value={auth}><CookieConsentContext.Provider value={consent}><RouterProvider router={router}/></CookieConsentContext.Provider></AuthContext.Provider></QueryClientProvider>);
