import './state';
import {createRoot} from 'react-dom/client';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {createBrowserRouter,RouterProvider} from 'react-router';
import {AppShell} from '@/components/app-shell';
import {BlueButtonHover} from '@/components/ui/blue-button-hover';
import {AuthContext} from '@/features/auth/auth-context';
import type {AuthContextValue} from '@/features/auth/auth-context';
import {CookieConsentContext} from '@/features/privacy/cookie-consent-context';
import type {CookieConsentContextValue} from '@/features/privacy/cookie-consent-context';
import {PublicHomePage} from '@/pages/home-page';
import {TotalLossAnalysisPage} from '@/pages/total-loss-analysis-page';
import {USER_ID,BASE} from './fixtures';
import {page} from './state';
import {Launcher} from './launcher';
import {Harness} from './harness';
import './styles.css';
const user={id:USER_ID,email:'owner@example.com',user_metadata:{full_name:'Case Owner'},app_metadata:{provider:'email'},aud:'authenticated',created_at:'2026-08-29T18:00:00.000Z'};
const session={access_token:'synthetic-access-token',refresh_token:'synthetic-refresh-token',expires_in:3600,token_type:'bearer' as const,user};
const noop=async()=>{};
const auth:AuthContextValue={auth:page==='home'?{status:'signedOut',session:null,user:null}:{status:'signedIn',identity:'permanent',session,user},ensureGuestSession:async()=>session,restoreSession:async()=>session,runTurnstileChallenge:noop as AuthContextValue['runTurnstileChallenge'],signInWithGoogle:noop,sendMagicLink:noop,completeAuthCallback:async()=>session,completeEmailAuthCallback:async()=>session,signOut:noop};
const consent:CookieConsentContextValue={consent:null,globalPrivacyControl:false,bannerVisible:false,preferencesOpen:false,acceptAll:noop,rejectNonEssential:noop,savePreferences:noop,openPreferences:noop,setPreferencesOpen:noop};

const router=createBrowserRouter(page==='launcher'?[{path:'/',element:<Launcher/>}]:[{element:<AppShell/>,children:[{path:`${BASE}/review/:stage`,element:<Harness accessToken={session.access_token}/>},{path:'/total-loss/cases/:caseId/analysis',element:<TotalLossAnalysisPage/>},{path:'/',element:<PublicHomePage/>}]}]);
const runtime=globalThis as typeof globalThis & {__reviewRoot?:ReturnType<typeof createRoot>;__reviewQueryClient?:QueryClient};const root=runtime.__reviewRoot||=createRoot(document.getElementById('root')!);const queryClient=runtime.__reviewQueryClient||=new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}});
root.render(<QueryClientProvider client={queryClient}><BlueButtonHover/><AuthContext.Provider value={auth}><CookieConsentContext.Provider value={consent}><RouterProvider router={router}/></CookieConsentContext.Provider></AuthContext.Provider></QueryClientProvider>);
