import {createRoot} from 'react-dom/client';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {createBrowserRouter,RouterProvider,Navigate,Outlet,Link} from 'react-router';
import {adminRoute} from '@/features/admin/admin-routes';
import {createSyntheticOperationsService} from './operations-fixtures';
import {BlueButtonHover} from '@/components/ui/blue-button-hover';
import {AuthContext,type AuthContextValue} from '@/features/auth/auth-context';
import {CookieConsentContext,type CookieConsentContextValue} from '@/features/privacy/cookie-consent-context';
import {AdminCaseOperationsDependenciesProvider} from '@/features/admin/case-operations/dependencies';
import {AdminDiminishedValueDependenciesProvider} from '@/features/admin/diminished-value/dependencies';
import {session,cases,detail} from './fixtures';
import './styles.css';
const noop=async()=>{};
const mode=new URLSearchParams(location.search).get('state')||'populated';
const result=async<T,>(value:T):Promise<T>=>{if(mode==='loading')return new Promise(()=>{});if(mode==='error')throw new Error('Synthetic connection failure');return value;};
const auth:AuthContextValue={auth:{status:'signedIn',identity:'permanent',session,user:session.user},ensureGuestSession:async()=>session,restoreSession:async()=>session,runTurnstileChallenge:async(run)=>run('synthetic-token'),signInWithGoogle:noop,signInWithApple:noop,sendMagicLink:noop,sendEmailCode:noop,completeEmailCode:async()=>session,completeAuthCallback:async()=>session,completeEmailAuthCallback:async()=>session,signOut:async()=>{location.href='/admin/cases?state=denied'}};
const consent:CookieConsentContextValue={consent:null,globalPrivacyControl:false,bannerVisible:false,preferencesOpen:false,acceptAll:noop,rejectNonEssential:noop,savePreferences:noop,openPreferences:noop,setPreferencesOpen:noop};
const ops={operationsService:createSyntheticOperationsService(mode),caseService:{isStaff:async()=>mode!=='denied',listCases:()=>result(mode==='empty'?[]:cases),getTotalLossCase:(id:string)=>result(detail(id))}};
const dv={caseService:{isStaff:async()=>mode!=='denied',listSubmittedCases:async()=>[],getSubmittedCase:async()=>null},documentService:{listDocuments:async()=>[],downloadDocument:async()=>{throw new Error('No documents in this synthetic preview')}}};
export function Preview(){return <><div className="preview-bar"><strong>Synthetic staff preview · fictional cases</strong><Link to="/admin">Overview</Link><label>Preview state <select aria-label="Preview state" value={mode} onChange={e=>{location.href=location.pathname+'?state='+e.target.value}}>{['populated','large','empty','loading','error','denied'].map(s=><option key={s}>{s}</option>)}</select></label></div><Outlet/></>}
const router=createBrowserRouter([{element:<Preview/>,children:[adminRoute,{path:'/',element:<Navigate to="/admin" replace/>},{path:'/admin/diminished-value/*',element:<Navigate to="/admin/cases" replace/>}]}]);
createRoot(document.getElementById('root')!).render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><BlueButtonHover/><AuthContext.Provider value={auth}><CookieConsentContext.Provider value={consent}><AdminCaseOperationsDependenciesProvider dependencies={ops}><AdminDiminishedValueDependenciesProvider dependencies={dv}><RouterProvider router={router}/></AdminDiminishedValueDependenciesProvider></AdminCaseOperationsDependenciesProvider></CookieConsentContext.Provider></AuthContext.Provider></QueryClientProvider>);
