/**
 * Generated from schemas/analysis/analysis-presentation.schema.json.
 * Source schema SHA-256: 5adecd6ee2381dc5463b93e511e52d954e98e2611548d8411b2d5e0ef4ae3cac.
 * Run `npm run generate:contracts` after changing the backend schema.
 * Do not edit this file directly.
 */

export type RunId = string;
export type UtcDateTime = string;
export type NonBlankString = string;
export type NullableNonBlankString = string | null;
export type NonnegativeMoney = Money & {
  cents?: number | null;
};
export type Money =
  | {
      cents: null;
      display: null;
    }
  | {
      cents: number;
      display: string;
    };
export type NullablePrimaryValueComparison = PrimaryValueComparison | null;
export type BasisPointValue =
  | {
      basisPoints: null;
      display: null;
    }
  | {
      basisPoints: number;
      display: string;
    };
export type NullableValueComparison = ValueComparison | null;
export type DispersionValue = BasisPointValue & {
  basisPoints?: number | null;
};
export type NullableAdjustmentDirection = AdjustmentDirection | null;
export type NullableEvidenceSection = EvidenceSection | null;
export type NullableCoverage = Coverage | null;
export type NullableDealer = Dealer | null;
export type NullableLifecycleEvidence = LifecycleEvidence | null;
export type NullableHistoricalCoverageDiagnostic = HistoricalCoverageDiagnostic | null;
export type NullableProviderMetadata = ProviderMetadata | null;

export interface AnalysisPresentationBase {
  presentationVersion: "1";
  runId: RunId;
  analysisCreatedAt: UtcDateTime;
  assessment: Assessment;
  vehicle: Vehicle;
  cccValuation: CccValuation;
  cccComparables: CccComparables;
  primaryExternalEvidence: NullableEvidenceSection;
  secondaryExternalEvidence: NullableEvidenceSection;
  comparablesUsed: ComparablesUsed;
  evidenceDiagnostics: EvidenceDiagnostics;
  findings: Finding[];
  /**
   * @minItems 1
   */
  limitations: [Limitation, ...Limitation[]];
  provenance: Provenance;
}
export interface Assessment {
  classification:
    | "INSUFFICIENT_EVIDENCE"
    | "NO_MATERIAL_DISCREPANCY"
    | "POTENTIAL_UNDERVALUE"
    | "MATERIAL_UNDERVALUE_SIGNAL"
    | "CONFLICTING_EVIDENCE";
  classificationLabel: NonBlankString;
  evidenceStrength: "LOW" | "MODERATE" | "STRONG";
  evidenceStrengthLabel: NonBlankString;
  evidenceBasis: "NONE" | "LOSS_DATE_HISTORICAL" | "CURRENT_MARKET";
  evidenceBasisLabel: NonBlankString;
  summary: NonBlankString;
}
export interface Vehicle {
  year: number;
  make: NonBlankString;
  model: NonBlankString;
  trim: NullableNonBlankString;
  mileage: number | null;
  lossDate: string | null;
  postalCode: NullableNonBlankString;
}
export interface CccValuation {
  valueCode: "CCC_ADJUSTED_VEHICLE_VALUE";
  valueLabel: NonBlankString;
  adjustedVehicleValue: NonnegativeMoney;
  explanation: NonBlankString;
  comparisonToPrimaryEvidence: NullablePrimaryValueComparison;
  supportingComparisons: SupportingComparisons;
}
export interface PrimaryValueComparison {
  label: NonBlankString;
  evidenceBasis: "LOSS_DATE_HISTORICAL" | "CURRENT_MARKET";
  firstValueLabel: NonBlankString;
  secondValueLabel: NonBlankString;
  firstValue: NonnegativeMoney;
  secondValue: NonnegativeMoney;
  difference: Money;
  differencePercent: BasisPointValue;
  cccPositionInExternalRange: "BELOW_OBSERVED_RANGE" | "WITHIN_OBSERVED_RANGE" | "ABOVE_OBSERVED_RANGE";
  cccPositionLabel: NonBlankString;
}
export interface SupportingComparisons {
  cccAdjustedMedianVsVehicleValuation: NullableValueComparison;
  cccAdvertisedMedianVsAdjustedMedian: NullableValueComparison;
  externalMedianVsCccAdjustedMedian: NullableValueComparison;
}
export interface ValueComparison {
  label: NonBlankString;
  firstValueLabel: NonBlankString;
  secondValueLabel: NonBlankString;
  firstValue: NonnegativeMoney;
  secondValue: NonnegativeMoney;
  difference: Money;
  differencePercent: BasisPointValue;
}
export interface CccComparables {
  summary: CccComparableSummary;
  rows: CccComparableRow[];
}
export interface CccComparableSummary {
  totalCount: number;
  advertisedPriceMissingCount: number;
  adjustedValueMissingCount: number;
  pairedValueCount: number;
  pairedValueMissingCount: number;
  fullyDisclosedAdjustmentCount: number;
  partiallyDisclosedAdjustmentCount: number;
  undisclosedAdjustmentCount: number;
  unavailableAdjustmentCount: number;
  advertisedPrices: PriceSummary;
  adjustedValues: PriceSummary;
  netAdjustments: MoneySummary;
  adjustmentDirection: NullableAdjustmentDirection;
}
export interface PriceSummary {
  count: number;
  minimumPrice: NonnegativeMoney;
  maximumPrice: NonnegativeMoney;
  medianPrice: NonnegativeMoney;
  range: NonnegativeMoney;
  medianAbsoluteDeviation: NonnegativeMoney;
  centralHalfRange: NonnegativeMoney;
  dispersion: DispersionValue;
}
export interface MoneySummary {
  count: number;
  minimum: Money;
  maximum: Money;
  median: Money;
  range: NonnegativeMoney;
}
export interface AdjustmentDirection {
  code:
    | "CCC_ADJUSTMENTS_REDUCE_COMPARABLE_VALUES"
    | "CCC_ADJUSTMENTS_INCREASE_COMPARABLE_VALUES"
    | "CCC_ADJUSTMENTS_NO_MEDIAN_CHANGE";
  label: NonBlankString;
  description: NonBlankString;
}
export interface CccComparableRow {
  index: number;
  comparableNumber: number | null;
  year: number | null;
  make: NullableNonBlankString;
  model: NullableNonBlankString;
  trim: NullableNonBlankString;
  vin: NullableNonBlankString;
  dealer: NullableNonBlankString;
  location: NullableNonBlankString;
  distanceMiles: number | null;
  mileage: number | null;
  advertisedPrice: NonnegativeMoney;
  cccAdjustedComparableValue: NonnegativeMoney;
  netAdjustment: Money;
  adjustments: CccAdjustments;
  adjustmentDisclosure: "full" | "partial" | "none" | "unavailable";
  adjustmentDisclosureLabel: NonBlankString;
  contributionPercent: number | null;
}
export interface CccAdjustments {
  package: Money;
  options: Money;
  mileage: Money;
  condition: Money;
}
export interface EvidenceSection {
  role: "PRIMARY" | "SECONDARY";
  evidenceBasis: "LOSS_DATE_HISTORICAL" | "CURRENT_MARKET";
  evidenceBasisLabel: NonBlankString;
  label: NonBlankString;
  description: NonBlankString;
  provider: ProviderMetadata;
  evidenceDate: string;
  coverage: NullableCoverage;
  resolvedCount: number;
  unresolvedCount: number;
  ambiguousCount: number;
  rankedCandidateCount: number;
  eligibleCandidateCount: number;
  ineligibleCount: number;
  identityMissingExcludedCount: number;
  duplicateIdentityExcludedCount: number;
  comparisonSetLimitExcludedCount: number;
  selectedCount: number;
  selectedWeakCount: number;
  prices: PriceSummary;
}
export interface ProviderMetadata {
  name: NonBlankString;
  version: NullableNonBlankString;
}
export interface Coverage {
  status: "SUPPORTED" | "OUT_OF_PROVIDER_RANGE";
  statusLabel: NonBlankString;
  asOfDate: string;
  historyWindowDays: number;
}
export interface ComparablesUsed {
  primary: (ExternalComparable & {
    evidenceRole?: "PRIMARY";
  })[];
  secondary: (ExternalComparable & {
    evidenceRole?: "SECONDARY";
    evidenceBasis?: "CURRENT_MARKET";
  })[];
}
export interface ExternalComparable {
  evidenceRole: "PRIMARY" | "SECONDARY";
  evidenceBasis: "LOSS_DATE_HISTORICAL" | "CURRENT_MARKET";
  source: string;
  sourceListingId: NullableNonBlankString;
  vin: NullableNonBlankString;
  year: number;
  make: NonBlankString;
  model: NonBlankString;
  trim: NullableNonBlankString;
  mileage: number | null;
  lossVehicleMileage: number | null;
  mileageDifferenceFromLossVehicle: number | null;
  advertisedPrice: NonnegativeMoney;
  dealer: NullableDealer;
  distanceMiles: number | null;
  rank: number;
  score: number;
  tier: "STRONG" | "GOOD" | "WEAK";
  tierLabel: NonBlankString;
  temporalBasis: "CURRENT_MARKET" | "LISTING_RECORD_ACTIVE_ON_DATE";
  temporalBasisLabel: NonBlankString;
  evidenceDate: string;
  lifecycleEvidence: NullableLifecycleEvidence;
}
export interface Dealer {
  name: NullableNonBlankString;
  city: NullableNonBlankString;
  state: NullableNonBlankString;
  postalCode: NullableNonBlankString;
}
export interface LifecycleEvidence {
  status: "RESOLVED";
  basis: "LISTING_RECORD_ACTIVE_ON_DATE";
  basisLabel: NonBlankString;
  evidenceDate: string;
  recordFirstSeenAt: string;
  recordLastSeenAt: string;
  sourceFirstSeenAt: string | null;
  sourceLastSeenAt: string | null;
}
export interface EvidenceDiagnostics {
  historicalCoverage: NullableHistoricalCoverageDiagnostic;
  exclusions: Exclusion[];
  historicalIssues: HistoricalIssue[];
}
export interface HistoricalCoverageDiagnostic {
  provider: ProviderMetadata;
  evidenceDate: string;
  status: "SUPPORTED" | "OUT_OF_PROVIDER_RANGE";
  statusLabel: NonBlankString;
  description: NonBlankString;
  asOfDate: string;
  historyWindowDays: number;
}
export interface Exclusion {
  code:
    | "AMBIGUOUS_HISTORICAL_RECORDS_EXCLUDED"
    | "UNRESOLVED_HISTORICAL_RECORDS_EXCLUDED"
    | "IDENTITY_MISSING_EXTERNAL_RECORDS_EXCLUDED"
    | "DUPLICATE_EXTERNAL_IDENTITIES_EXCLUDED"
    | "EXTERNAL_COMPARISON_SET_BOUNDED"
    | "INELIGIBLE_EXTERNAL_RECORDS_EXCLUDED";
  evidenceBasis: "LOSS_DATE_HISTORICAL" | "CURRENT_MARKET";
  count: number;
  label: NonBlankString;
  description: NonBlankString;
  pricesContributed: false;
}
export interface HistoricalIssue {
  status: "UNRESOLVED" | "AMBIGUOUS";
  statusLabel: NonBlankString;
  reason:
    | "RECORD_INTERVAL_BEFORE_EVIDENCE_DATE"
    | "RECORD_INTERVAL_AFTER_EVIDENCE_DATE"
    | "MISSING_RECORD_TIMESTAMPS"
    | "MALFORMED_RECORD_TIMESTAMPS"
    | "INCONSISTENT_RECORD_TIMESTAMPS"
    | "INVALID_RECORD_INTERVAL"
    | "MALFORMED_SOURCE_TIMESTAMPS"
    | "INCONSISTENT_SOURCE_TIMESTAMPS"
    | "INVALID_SOURCE_INTERVAL"
    | "RECORD_OUTSIDE_SOURCE_INTERVAL"
    | "NO_RECORD_ACTIVE_ON_EVIDENCE_DATE"
    | "MISSING_LISTING_IDENTITY"
    | "UNVERIFIABLE_RECORD_CONTEXT"
    | "MULTIPLE_SOURCE_RECORDS_ON_EVIDENCE_DATE"
    | "PAGINATION_SAFETY_LIMIT_REACHED"
    | "INCOMPLETE_PROVIDER_PAGINATION";
  reasonLabel: NonBlankString;
  description: NonBlankString;
  vin: NullableNonBlankString;
  sourceListingId: NullableNonBlankString;
  pricesContributed: false;
}
export interface Finding {
  code:
    | "MISSING_CCC_VEHICLE_VALUATION"
    | "NONPOSITIVE_CCC_VEHICLE_VALUATION"
    | "INSUFFICIENT_RESOLVED_EXTERNAL_EVIDENCE"
    | "EXTERNAL_MEDIAN_ZERO"
    | "EXTERNAL_MEDIAN_ABOVE_CCC"
    | "EXTERNAL_MEDIAN_BELOW_CCC"
    | "EXTERNAL_MEDIAN_EQUALS_CCC"
    | "CCC_BELOW_EXTERNAL_RANGE"
    | "CCC_WITHIN_EXTERNAL_RANGE"
    | "CCC_ABOVE_EXTERNAL_RANGE"
    | "EXTERNAL_MARKET_HIGH_DISPERSION"
    | "CCC_AND_EXTERNAL_EVIDENCE_CONSISTENT"
    | "HISTORICAL_PRIMARY_EVIDENCE"
    | "CURRENT_PRIMARY_EVIDENCE"
    | "CURRENT_MARKET_ONLY"
    | "CURRENT_EVIDENCE_SECONDARY"
    | "HISTORICAL_CURRENT_SIGNALS_CONFLICT"
    | "HISTORICAL_EVIDENCE_OUT_OF_PROVIDER_RANGE"
    | "AMBIGUOUS_HISTORICAL_RECORDS_EXCLUDED"
    | "UNRESOLVED_HISTORICAL_RECORDS_EXCLUDED"
    | "IDENTITY_MISSING_EXTERNAL_RECORDS_EXCLUDED"
    | "DUPLICATE_EXTERNAL_IDENTITIES_EXCLUDED"
    | "EXTERNAL_COMPARISON_SET_BOUNDED"
    | "CCC_ADJUSTMENTS_REDUCE_COMPARABLE_VALUES"
    | "CCC_ADJUSTMENTS_INCREASE_COMPARABLE_VALUES"
    | "CCC_ADJUSTMENTS_NO_MEDIAN_CHANGE"
    | "POTENTIAL_GAP_THRESHOLD_MET"
    | "MATERIAL_GAP_THRESHOLD_MET";
  label: NonBlankString;
  description: NonBlankString;
}
export interface Limitation {
  code:
    | "NOT_AN_INDEPENDENT_APPRAISAL"
    | "DOES_NOT_CALCULATE_LEGAL_SETTLEMENT"
    | "POLICY_THRESHOLDS_NOT_LEGAL_STANDARDS"
    | "NEGOTIATION_OUTPUT_NOT_INCLUDED"
    | "ADVERTISED_PRICES_NOT_TRANSACTIONS"
    | "NO_INDEPENDENT_MILEAGE_ADJUSTMENT"
    | "NO_INDEPENDENT_CONDITION_ADJUSTMENT"
    | "NO_INDEPENDENT_OPTIONS_ADJUSTMENT"
    | "PROVIDER_COVERAGE_LIMITED"
    | "CURRENT_LISTINGS_NOT_LOSS_DATE_EVIDENCE"
    | "HISTORICAL_DATE_LEVEL_ONLY"
    | "HISTORICAL_OUT_OF_RANGE_NOT_NO_MARKET"
    | "AMBIGUOUS_HISTORICAL_EVIDENCE_NOT_PRICED"
    | "UNRESOLVED_HISTORICAL_EVIDENCE_NOT_PRICED"
    | "BOUNDED_EXTERNAL_COMPARISON_SET";
  label: NonBlankString;
  description: NonBlankString;
}
export interface Provenance {
  runId: RunId;
  presentationVersion: "1";
  analysisRunSchemaVersion: NonBlankString;
  orchestrationAnalysisVersion: NonBlankString;
  discrepancyAnalysisVersion: NonBlankString;
  comparableScoringVersion: NonBlankString;
  createdAt: UtcDateTime;
  requestDigest: RequestDigest;
  providers: Providers;
}
export interface RequestDigest {
  algorithm: "SHA-256";
  value: string;
  label: NonBlankString;
  description: NonBlankString;
}
export interface Providers {
  current: NullableProviderMetadata;
  historical: NullableProviderMetadata;
}

type HistoricalEvidenceSection = Omit<
  EvidenceSection,
  "role" | "evidenceBasis" | "coverage"
> & {
  role: "PRIMARY";
  evidenceBasis: "LOSS_DATE_HISTORICAL";
  coverage: Coverage & { status: "SUPPORTED" };
};

type CurrentEvidenceSection<Role extends "PRIMARY" | "SECONDARY"> = Omit<
  EvidenceSection,
  | "role"
  | "evidenceBasis"
  | "coverage"
  | "unresolvedCount"
  | "ambiguousCount"
> & {
  role: Role;
  evidenceBasis: "CURRENT_MARKET";
  coverage: null;
  unresolvedCount: 0;
  ambiguousCount: 0;
};

type HistoricalExternalComparable = Omit<
  ExternalComparable,
  | "evidenceRole"
  | "evidenceBasis"
  | "temporalBasis"
  | "lifecycleEvidence"
> & {
  evidenceRole: "PRIMARY";
  evidenceBasis: "LOSS_DATE_HISTORICAL";
  temporalBasis: "LISTING_RECORD_ACTIVE_ON_DATE";
  lifecycleEvidence: LifecycleEvidence;
};

type CurrentExternalComparable<Role extends "PRIMARY" | "SECONDARY"> = Omit<
  ExternalComparable,
  | "evidenceRole"
  | "evidenceBasis"
  | "temporalBasis"
  | "lifecycleEvidence"
> & {
  evidenceRole: Role;
  evidenceBasis: "CURRENT_MARKET";
  temporalBasis: "CURRENT_MARKET";
  lifecycleEvidence: null;
};

type HistoricalExclusionCode =
  | "AMBIGUOUS_HISTORICAL_RECORDS_EXCLUDED"
  | "UNRESOLVED_HISTORICAL_RECORDS_EXCLUDED";

type SchemaExclusion =
  | (Omit<Exclusion, "code" | "evidenceBasis"> & {
      code: HistoricalExclusionCode;
      evidenceBasis: "LOSS_DATE_HISTORICAL";
    })
  | (Omit<Exclusion, "code"> & {
      code: Exclude<Exclusion["code"], HistoricalExclusionCode>;
    });

type AnalysisPresentationCommon = Omit<
  AnalysisPresentationBase,
  | "assessment"
  | "primaryExternalEvidence"
  | "secondaryExternalEvidence"
  | "comparablesUsed"
  | "evidenceDiagnostics"
> & {
  evidenceDiagnostics: Omit<EvidenceDiagnostics, "exclusions"> & {
    exclusions: SchemaExclusion[];
  };
};

type AnalysisPresentationWithoutPrimaryEvidence =
  AnalysisPresentationCommon & {
    assessment: Assessment & { evidenceBasis: "NONE" };
    primaryExternalEvidence: null;
    secondaryExternalEvidence: null;
    comparablesUsed: { primary: []; secondary: [] };
    cccValuation: Omit<CccValuation, "comparisonToPrimaryEvidence"> & {
      comparisonToPrimaryEvidence: null;
    };
  };

type HistoricalAnalysisPresentation = AnalysisPresentationCommon & {
  assessment: Assessment & { evidenceBasis: "LOSS_DATE_HISTORICAL" };
  primaryExternalEvidence: HistoricalEvidenceSection;
};

type AnalysisPresentationWithHistoricalEvidence =
  HistoricalAnalysisPresentation &
    (
      | {
          secondaryExternalEvidence: null;
          comparablesUsed: {
            primary: HistoricalExternalComparable[];
            secondary: [];
          };
        }
      | {
          secondaryExternalEvidence: CurrentEvidenceSection<"SECONDARY">;
          comparablesUsed: {
            primary: HistoricalExternalComparable[];
            secondary: CurrentExternalComparable<"SECONDARY">[];
          };
        }
    );

type AnalysisPresentationWithCurrentEvidence = AnalysisPresentationCommon & {
  assessment: Assessment & { evidenceBasis: "CURRENT_MARKET" };
  primaryExternalEvidence: CurrentEvidenceSection<"PRIMARY">;
  secondaryExternalEvidence: null;
  comparablesUsed: {
    primary: CurrentExternalComparable<"PRIMARY">[];
    secondary: [];
  };
};

export type AnalysisPresentation =
  | AnalysisPresentationWithoutPrimaryEvidence
  | AnalysisPresentationWithHistoricalEvidence
  | AnalysisPresentationWithCurrentEvidence;
