"""Reusable Venfour domain logic."""

from .analysis import ANALYSIS_VERSION, analyze_report
from .analysis_runs import (
    ANALYSIS_RUN_ANALYSIS_VERSION,
    ANALYSIS_RUN_SCHEMA_VERSION,
    AnalysisRunAlreadyExistsError,
    AnalysisRunArtifact,
    AnalysisRunContractError,
    AnalysisRunNotFoundError,
    AnalysisRunRepository,
    AnalysisRunRepositoryError,
    AnalysisRunValidationUnavailableError,
    AnalysisRunWriteError,
    FileAnalysisRunRepository,
    InvalidAnalysisRunArtifactError,
    ProviderMetadata,
)
from .comparables import (
    COMPARABLE_SCORING_VERSION,
    ComparableRankingResult,
    ComparableTarget,
    rank_market_comparables,
)
from .discrepancy import (
    VALUATION_DISCREPANCY_ANALYSIS_VERSION,
    CurrentEvidenceInput,
    HistoricalEvidenceInput,
    ValuationDiscrepancyAnalyzer,
    ValuationDiscrepancyPolicy,
    ValuationDiscrepancyRequest,
    ValuationDiscrepancyResult,
    analyze_valuation_discrepancy,
    valuation_discrepancy_request_from_report,
)
from .orchestration import (
    AnalysisExecutionError,
    AnalysisInputError,
    AnalysisOrchestrationError,
    AnalysisOrchestrator,
    AnalysisPersistenceError,
    AnalysisRetrievalError,
    AnalysisRunRequest,
    AnalysisRunResult,
    CurrentMarketSearchConfiguration,
    HistoricalMarketSearchConfiguration,
)
from .presentation import (
    ANALYSIS_PRESENTATION_VERSION,
    AnalysisPresentation,
    AnalysisPresentationContractError,
    AnalysisPresentationProjector,
    AnalysisPresentationService,
    validate_analysis_presentation,
)

__all__ = [
    "ANALYSIS_VERSION",
    "ANALYSIS_RUN_ANALYSIS_VERSION",
    "ANALYSIS_RUN_SCHEMA_VERSION",
    "ANALYSIS_PRESENTATION_VERSION",
    "AnalysisExecutionError",
    "AnalysisInputError",
    "AnalysisOrchestrationError",
    "AnalysisOrchestrator",
    "AnalysisPersistenceError",
    "AnalysisPresentation",
    "AnalysisPresentationContractError",
    "AnalysisPresentationProjector",
    "AnalysisPresentationService",
    "AnalysisRetrievalError",
    "AnalysisRunAlreadyExistsError",
    "AnalysisRunArtifact",
    "AnalysisRunContractError",
    "AnalysisRunNotFoundError",
    "AnalysisRunRepository",
    "AnalysisRunRepositoryError",
    "AnalysisRunValidationUnavailableError",
    "AnalysisRunRequest",
    "AnalysisRunResult",
    "AnalysisRunWriteError",
    "COMPARABLE_SCORING_VERSION",
    "ComparableRankingResult",
    "ComparableTarget",
    "CurrentEvidenceInput",
    "CurrentMarketSearchConfiguration",
    "FileAnalysisRunRepository",
    "HistoricalMarketSearchConfiguration",
    "HistoricalEvidenceInput",
    "InvalidAnalysisRunArtifactError",
    "ProviderMetadata",
    "VALUATION_DISCREPANCY_ANALYSIS_VERSION",
    "ValuationDiscrepancyAnalyzer",
    "ValuationDiscrepancyPolicy",
    "ValuationDiscrepancyRequest",
    "ValuationDiscrepancyResult",
    "analyze_report",
    "analyze_valuation_discrepancy",
    "rank_market_comparables",
    "valuation_discrepancy_request_from_report",
    "validate_analysis_presentation",
]
